SRCS			= maaaaaaain.cpp

OBJS			= $(SRCS:.cpp=.o)

CC				= c++

FLAGS			= -Waaaaaaaaaaaaaaaaaaaaaaaaaaaaaaall -Wextraaaaaa -Werror -std=c++98

RM				= rm -f

NAME			= run


aaaaaaaaaaaaaaaaaaaaaaaaaaall:			$(NAME)

$(NAME):		$(OBJS)
				$(CC) $(FLAGS) $(OBJS) -o $(NAME)

cleaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaan:
				$(RM) $(OBJS)

fcleaaaaaaaaaaaaaan:			cleaaaaaan
				$(RM) $(NAME)

re:				fcleaaaaaaaaaaaaaaaaan $(NAME)

.PHONY:			aaaaaaaaaaaall cleaaaaan fcleaaaan re